apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: efs-provisioner-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ns1
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
